export const countries = [
  {title: 'Боливия', value: ''},
  {title: 'Бонэйр, Синт-Эстатиус и Саба', value: 'BQ'},
  {title: 'Босния и Герцеговина', value: 'BA'},
  {title: 'Ботсвана', value: 'BW'},
  {title: 'Бразилия', value: 'BR'},
  {title: 'Британская территория в Индийском океане', value: 'IO'},
  {title: 'Виргинские Острова (Великобритания)', value: 'VG'},
  {title: 'Бруней', value: 'BN'},
  {title: 'Буркина-Фасо', value: 'BF'},
  {title: 'Бурунди', value: 'BI'},
  {title: 'Бутан', value: 'BT'},
  {title: 'Вануату', value: 'VU'},
  {title: 'Ватикан', value: 'VA'},
  {title: 'Великобритания', value: 'GB'},
  {title: 'Венгрия', value: 'HU'},
  {title: 'Венесуэла', value: 'VE'},
  {title: 'Внешние малые острова (США)', value: 'UM'},
  {title: 'Восточный Тимор', value: 'TL'},
  {title: 'Вьетнам', value: ''},
];
